print("My name is Austin")
print("I am 18 years old")
print("i come from Kiambu county")
print("I love playing football")
print("-----------------")
print("**************")
print("##################")
